serverPort                  : 8080
dbHost                      : localhost
dbPort                      : 5432
dbUser                      : index_user
dbPassword                  : "1234321"
dbName                      : index_db
cachePath                   : "./ergveinCache"
BTCNodeIsTestnet            : true
BTCNodeHost                 : localhost
BTCNodePort                 : 18332
BTCNodeUser                 : bitcoinrpc
BTCNodePassword             : password
ERGONodeHost                : localhost
ERGONodePort                : 9052
blockchainScanDelay         : 1000000
dbLog                       : false
pubScriptHistoryScan        : false
ownPeerAddress              : "http://localhost"
knownPeers                  :
                              - "https://ergvein-indexer1.hxr.team"
                              - "https://ergvein-indexer2.hxr.team"
peerConnectionRetryTimeout  : 86400