serverPort               : 8085
serverTcpPort            : 8667
filtersDbPath            : "./ergveinDb"
indexerDbPath            : "./indexerDb"
BTCNodeIsTestnet         : true
BTCNodeHost              : localhost
BTCNodePort              : 18332
BTCNodeUser              : bitcoinrpc
BTCNodePassword          : password
ERGONodeHost             : localhost
ERGONodePort             : 9052
blockchainScanDelay      : 1000000
ownPeerAddress           : null
knownPeers               :
                           - "https://ergvein-indexer1.hxr.team"
                           - "https://ergvein-indexer2.hxr.team"
peerActualizationDelay   : 10000000
peerActualizationTimeout : 86400
